apiVersion: v1
kind: Service
metadata:
  name: frontend-10
  namespace: production
  labels:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
spec:
  type: LoadBalancer
  selector:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 10-frontend-ingress
  namespace: production
  labels:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
spec:
  rules:
  - host: wip.camp
    http:
      paths:
      - backend:
          serviceName: frontend-10
          servicePort: 80