apiVersion: v1
kind: PersistentVolume
metadata:
  name: wip-api-staging-volume
  namespace: staging
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.wip.camp
    path: "/mnt/wip-camp/staging/api"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wip-api-volume-claim
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      app: wip-api
      organize: wipcamp10
      tier: backend
