apiVersion: v1
kind: PersistentVolume
metadata:
  name: wip-api-production-volume
  namespace: production
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
    env: production
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.wip.camp
    path: "/mnt/wip-camp/production/api"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wip-api-volume-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: wip-api
      organize: wipcamp10
      tier: backend
      env: production
