apiVersion: v1
kind: ConfigMap
metadata:
  name: wip-api-config
  namespace: production
data:
  GENERAL_ENV: |
    APP_NAME=WIP-API
    APP_URL=api.wip.camp
    APP_ENV=local
    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    SESSION_DRIVER=file
    SESSION_LIFETIME=120
    QUEUE_DRIVER=sync
    DB_CONNECTION=mysql
    DB_HOST=db-service
    DB_PORT=3306
    DB_DATABASE=laravel_api
    DB_USERNAME=laravel_api
    APP_DEBUG=false
    APP_LOG_LEVEL=debug
  php_post_size.conf: |
    post_max_size=5M
    


---

apiVersion: v1
kind: ReplicationController
metadata:
  name: wip-api
  namespace: production
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
spec:
  replicas: 4
  selector:
    app: wip-api
    organize: wipcamp10
    tier: backend
  template:
    metadata:
      labels:
        app: wip-api
        organize: wipcamp10
        tier: backend
    spec:
      containers:
      - name: wip-api-app
        image: registry.wip.camp/wip-api:master-4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
        env:
        - name: GENERAL_ENV
          valueFrom:
            configMapKeyRef:
              name: wip-api-config
              key: GENERAL_ENV
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: app-key
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db-password
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: sentry-dsn
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: jwt-secret
        volumeMounts:
        - name: api-volume
          mountPath: "/app/storage"
        - name: php-post-config
          mountPath: /usr/local/etc/php/conf.d/php_post_size.conf
          subPath: php_post_size.conf
      volumes:
      - name: api-volume
        persistentVolumeClaim:
          claimName: wip-api-volume-claim
      - name: php-post-config
        configMap:
          name: wip-api-config

---

apiVersion: v1
kind: Service
metadata:
  name: wip-api
  namespace: production
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: wip-api
    organize: wipcamp10
    tier: backend
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wip-api
  namespace: production
  labels:
    app: wip-api
    organize: wipcamp10
    tier: backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5M"
spec:
  rules:
  - host: api.wip.camp
    http:
      paths:
      - backend:
          serviceName: wip-api
          servicePort: 80
