apiVersion: v1
kind: ReplicationController
metadata:
  name: wip-itim
  namespace: staging
  labels:
    app: wip-itim
    organize: wipcamp10
    tier: frontend
spec:
  replicas: 2
  selector:
    app: wip-itim
    organize: wipcamp10
    tier: frontend
  template:
    metadata:
      labels:
        app: wip-itim
        organize: wipcamp10
        tier: frontend
    spec:
      containers:
      - name: wip-itim
        image: registry.wip.camp/wip-itim:master
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "https://api.kati.wip.camp/api/v1"
---

apiVersion: v1
kind: Service
metadata:
  name: wip-itim
  namespace: staging
  labels:
    app: wip-itim
    organize: wipcamp10
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: wip-itim
    organize: wipcamp10
    tier: frontend
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wip-itim
  namespace: staging
  labels:
    app: wip-itim
    organize: wipcamp10
    tier: frontend
spec:
  rules:
  - host: itim.kati.wip.camp
    http:
      paths:
      - backend:
          serviceName: wip-itim
          servicePort: 80
