apiVersion: v1
kind: ReplicationController
metadata:
  name: 10-frontend
  namespace: staging
  labels:
    app: 10-frontend
    organize: wipcamp10
    tier: frontend
spec:
  replicas: 2
  selector:
    app: 10-frontend
    organize: wipcamp10
    tier: frontend
  template:
    metadata:
      labels:
        app: 10-frontend
        tier: frontend
        organize: wipcamp10
    spec:
      containers:
      - name: 10-frontend
        image: registry.wip.camp/10-frontend:master
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-10
  namespace: staging
  labels:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
spec:
  type: LoadBalancer
  selector:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 10-frontend-ingress
  namespace: staging
  labels:
    app: 10-frontend
    tier: frontend
    organize: wipcamp10
spec:
  rules:
  - host: frontend.kati.wip.camp
    http:
      paths:
      - backend:
          serviceName: frontend-10
          servicePort: 80
